### ISSUE TITLE
Implementing Call.Factory

### ISSUE THREAD

**Issue by pushbit** [apkelly/GoogleAppEngineOkHttp#1]
Have you considered creating a `GoogleAppEngineOkHttpClient` class which implements `Call.Factory` (like the example in the README)?  Then applications could simply inject (or otherwise provide) a single instance of `OkHttpClient` or `GoogleAppEngineOkHttpClient` as needed and it would be nice and consistent.  `GoogleAppEngineCall` could then be package-private.

**Comment by apkelly** [comment]
Hi Pushbit,

I hadn't considered that, but its a good suggestion.

Thanks for your interest in the library.

Andy.
