### ISSUE TITLE
retrofit 2.20/okhttp 3.6.0 compatibility?

### ISSUE THREAD

**Issue by chirstius** [apkelly/GoogleAppEngineOkHttp#3]
Is there any work being done to provide compatibility with these newer releases?

Bringing the current implementation in causes a conflict with the clone() method between Object and the Call interface:

Exception CloneNotSupportedException in throws clause of Object.clone() is not compatible with Call.clone()
The inherited method Object.clone() cannot hide the public abstract method in Call

I've gotten around this for the moment by implementing clone() and just eating the exception, but that seems very wrong.

**Comment by apkelly** [comment]
Hi Chuck,

Thanks for bringing this to my attention. I merged a pull request recently but didn't do any testing myself. I'll try and take a look and fix as required.

Andy.

**Comment by pushbit** [comment]
Chuck, have you pulled the latest commit?  I think I ran into the same issue and added `GoogleAppEngineCall.clone()`, which should resolve it.

On a similar note, OkHttp 3.8.0 now requires response messages and I'm working on a PR to fix that as well.

**Comment by apkelly** [comment]
@pushbit is this fixed by PR #5 ?

**Comment by pushbit** [comment]
No, I believe it was already fixed by PR #2.

**Comment by chirstius** [comment]
Was away on a vacation, have not pulled the updated version, Will give it a try - thank you!

**Comment by chirstius** [comment]
Seems good for the clone() issues. Though the class and constructor were no longer public which caused me some visibility issues. Was that an intentional change?

**Comment by pushbit** [comment]
Yeah, the idea is that instead of implementing `Call.Factory` you can just create an instance of `GoogleAppEngineOkHttpClient`, which does that for you.

**Comment by chirstius** [comment]
Ah, ok, my usage was from before the Client was added so hadn't been using it. I can switch over. This can be marked as closed. Seems to work just fine.
